apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-config
spec:
  selector:
    matchLabels:
      app: my-app-with-config
  template:
    metadata:
      labels:
        app: my-app-with-config
    spec:
      containers:
      - name: my-app-with-config
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        # Define the environment variable
          - name: SOME_VALUE
            valueFrom:
               configMapKeyRef:
                name: myconfig           	# The ConfigMap this value comes from.
                key: some_key 
# The key to fetch.
